repo: "letter-looper"
canvasCourse: javascript

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 1
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - 'script[src="js/main.js"]'
    hasNot:
      - ["link", "CSS isn’t necessary to complete this assignment"]
      - [
          "body :not(script)",
          "The `<script>` tag should be the only tag inside `<body>` — no other HTML is needed",
        ]

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true
    search:
      - "var"
      - "prompt"
      - "for"
      - ["(9|10|11)", "The letter should be output 10 times."]
      - "document.write"
      - "<br>"

functionality:
  - path: "index.html"
    setup: |
      window.prompt = function () {
        return 'a';
      }
    tests:
      - |
        let content = document.body.textContent.trim().replace(/[\s\r\n\t]/g, '');

        if (content.length !== 10) fail(`There are ${content.length} letters written out to the page but there should be 10`);
        pass();
